
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/infrastructure"
    schedule:
      interval: "daily"

  - package-ecosystem: "maven"
    directory: "/software/FunctionRandomBibleVerse"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"