logging.level.org.springframework.cloud=DEBUG

# Configure Spring Cloud Function
spring.cloud.function.definition=randomBibleVerseHandler,aboutHandler

# Bible data storage
bibleverse.s3.bucket-name=${BIBLEVERSE_S3_BUCKET_NAME:bible-verse-data-files}
bibleverse.s3.region=${AWS_REGION:us-east-1}
